export const CREATE_XML_AND_SEND_MAIL_SUCCESS =
  'CREATE_XML_AND_SEND_MAIL_SUCCESS';
export const CREATE_XML_AND_SEND_MAIL_FAIL = 'CREATE_XML_AND_SEND_MAIL_FAIL';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_FAIL = 'GET_CONTACT_LIST_FAIL';
export const CREATE_OR_UPDATE_CONTACT_SUCCESS =
  'CREATE_OR_UPDATE_CONTACT_SUCCESS';
export const CREATE_OR_UPDATE_CONTACT_FAIL = 'CREATE_OR_UPDATE_CONTACT_FAIL';
export const SET_CREATE_XML_TO_NULL = 'SET_CREATE_XML_TO_NULL';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const SET_SHOW_LOADER = 'SET_SHOW_LOADER';
export const SET_CREATE_OR_UPDATE_CONTACT_TO_NULL =
  'SET_CREATE_OR_UPDATE_CONTACT_TO_NULL';
export const GET_CONTACT_BY_PRSNUM_SUCCESS = 'GET_CONTACT_BY_PRSNUM_SUCCESS';
export const GET_CONTACT_BY_PRSNUM_FAIL = 'GET_CONTACT_BY_PRSNUM_FAIL';
export const GET_CONTACT_DECODE_SUCCESS = 'GET_CONTACT_DECODE_SUCCESS';
export const GET_CONTACT_DECODE_FAIL = 'GET_CONTACT_DECODE_FAIL';
