export const GET_MEETING_LIST_SUCCESS = 'GET_MEETING_LIST_SUCCESS';
export const GET_MEETING_LIST_FAIL = 'GET_MEETING_LIST_FAIL';
export const CREATE_OR_UPDATE_MEETING_SUCCESS =
  'CREATE_OR_UPDATE_MEETING_SUCCESS';
export const CREATE_OR_UPDATE_MEETING_FAIL = 'CREATE_OR_UPDATE_MEETING_FAIL';
export const SET_CREATE_MEETING_TO_NULL = 'SET_CREATE_MEETING_TO_NULL';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const SET_SHOW_LOADER = 'SET_SHOW_LOADER';

export const GET_MEETING_BY_ID_SUCCESS = 'GET_MEETING_BY_ID_SUCCESS';
export const GET_MEETING_BY_ID_FAIL = 'GET_MEETING_BY_ID_FAIL';
export const GET_CONTACT_DECODE_SUCCESS = 'GET_CONTACT_DECODE_SUCCESS';
export const GET_CONTACT_DECODE_FAIL = 'GET_CONTACT_DECODE_FAIL';
